//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISportService")]
    public interface ISportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISportService/SportsList", ReplyAction="http://tempuri.org/ISportService/SportsListResponse")]
        System.Data.DataTable SportsList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISportService/SportsList", ReplyAction="http://tempuri.org/ISportService/SportsListResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> SportsListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISportService/GetSportsList", ReplyAction="http://tempuri.org/ISportService/GetSportsListResponse")]
        System.Data.DataTable GetSportsList(string continent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISportService/GetSportsList", ReplyAction="http://tempuri.org/ISportService/GetSportsListResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetSportsListAsync(string continent);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISportServiceChannel : DataLayer.ServiceReference1.ISportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SportServiceClient : System.ServiceModel.ClientBase<DataLayer.ServiceReference1.ISportService>, DataLayer.ServiceReference1.ISportService {
        
        public SportServiceClient() {
        }
        
        public SportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable SportsList() {
            return base.Channel.SportsList();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SportsListAsync() {
            return base.Channel.SportsListAsync();
        }
        
        public System.Data.DataTable GetSportsList(string continent) {
            return base.Channel.GetSportsList(continent);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetSportsListAsync(string continent) {
            return base.Channel.GetSportsListAsync(continent);
        }
    }
}
